env:
  TERM: xterm-256color # alacritty

# window:
#   decorations: full # full | none
#   opacity: 1
#   startup_mode: Windowed # Windowed | Maximized | Fullscreen
#   title: Alacritty
#   dynamic_title: true
#   decorations_theme_variant: None # `Dark`, `Light`, and `None`

# scrolling:
#   history: 10000 # Max scrollbar buffer, '0' means disable scroll
#   multiplier: 3

font:
  size: 8
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: "0x1a1b26"
    foreground: "0xc0caf5"

  # Normal colors
  normal:
    black: "0x15161e"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xa9b1d6"

  # Bright colors
  bright:
    black: "0x414868"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xc0caf5"

  indexed_colors:
    - { index: 16, color: "0xff9e64" }
    - { index: 17, color: "0xdb4b4b" }

cursor:
  style:
    shape: Block # Block | Underline | Beam
    blinking: On # Never | Off | On | Always
