env:
  TERM: xterm-256color # alacritty

window:
  # dimensions:
  #   columns: 0
  #   lines: 0
  # position:
  #   x: 0
  #   y: 0
  # padding:
  #   x: 0
  #   y: 0
  decorations: full # full | none
  opacity: 0.9
  startup_mode: Windowed # Windowed | Maximized | Fullscreen
  title: Alacritty
  dynamic_title: true
  decorations_theme_variant: None # `Dark`, `Light`, and `None`

scrolling:
  history: 10000 # Max scrollbar buffer, '0' means disable scroll
  multiplier: 3

font:
  size: 7.5
  # builtin_box_drawing: false
  draw_bold_text_with_bright_colors: false
  normal:
    # family: FiraCode Nerd Font
    family: JetBrainsMono Nerd Font
    style: Regular

colors:
  primary:
    # background: "#1E1E2E"
    background: "#181825"
    foreground: "#c5c8c6"

cursor:
  style:
    shape: Block # Block | Underline | Beam
    blinking: On # Never | Off | On | Always
