env:
  TERM: xterm-256color # alacritty

window:
  # dimensions:
  #   columns: 0
  #   lines: 0
  # position:
  #   x: 0
  #   y: 0
  # padding:
  #   x: 0
  #   y: 0
  decorations: full # full | none
  opacity: 0.9
  startup_mode: Windowed # Windowed | Maximized | Fullscreen
  title: Alacritty
  dynamic_title: true
  decorations_theme_variant: None # `Dark`, `Light`, and `None`

scrolling:
  history: 10000 # Max scrollbar buffer, '0' means disable scroll
  multiplier: 3

font:
  size: 7.5
  # builtin_box_drawing: false
  draw_bold_text_with_bright_colors: false
  normal:
    # family: FiraCode Nerd Font
    family: JetBrainsMono Nerd Font
    style: Regular

# colors:
#   primary:
#     # background: "#1E1E2E"
#     background: "#181825"
#     foreground: "#c5c8c6"

# TokyoNight Alacritty Colors
colors:
  # Default colors
  primary:
    background: "0x1a1b26"
    foreground: "0xc0caf5"

  # Normal colors
  normal:
    black: "0x15161e"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xa9b1d6"

  # Bright colors
  bright:
    black: "0x414868"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xc0caf5"

  indexed_colors:
    - { index: 16, color: "0xff9e64" }
    - { index: 17, color: "0xdb4b4b" }

cursor:
  style:
    shape: Block # Block | Underline | Beam
    blinking: On # Never | Off | On | Always
