live_config_reload = true

[env]
TERM             = "xterm-256color"

[font]
size             = 10

[font.normal]
family           = "JetBrainsMono Nerd Font"
style            = "Regular"

[window]
dynamic_padding           = true
opacity                   = 0.93
blur                      = true
decorations               = "Full"
# decorations_theme_variant = "Dark"

[colors]
transparent_background_colors = false

[colors.cursor]
text            = "CellBackground"
cursor          = "CellForeground"

[colors.vi_mode_cursor]
text            = "CellBackground"
cursor          = "#ff9e64"

[colors.primary]
background      = "#202027"
foreground      = "#fcfcfc"

[[colors.indexed_colors]]
color           = "#ff9e64"
index           = 16

[[colors.indexed_colors]]
color           = "#db4b4b"
index           = 17

[colors.bright]
black           = "#6C6168"
red             = "#F29BA7"
green           = "#a8be81"
yellow          = "#F3DDA0"
blue            = "#86AACC"
magenta         = "#D0B1C8"
cyan            = "#C9E4F6"
white           = "#E3F2FA"

[colors.normal]
black           = "#1c1d22"
red             = "#EA7A95"
green           = "#a8be81"
yellow          = "#eccc81"
blue            = "#5d81ab"
magenta         = "#b18eab"
cyan            = "#A6C9E5"
white           = "#FBF1F5"

[cursor.style]
blinking        = "Always"
shape           = "Block"

[mouse]
hide_when_typing          = true

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  # { key = "U", mods = "Control|Shift", action = "ToggleViMode" },
]
