#!/usr/bin/env zsh
#shellcheck disable=2181

git_purge_branch() {
	branch="$1"
	dot push -d origin "$branch"
	dot branch -D "$branch"
	if [ ! $? -eq 0 ]; then
		warn " failed to remove branch $branch"
	else
		okay " branch $branch removed"
	fi
}

## @ref https://stackoverflow.com/questions/10312521/how-do-i-fetch-all-git-branches
git_sync_all() {
	git branch -r | grep -v '\->' | sed "s,\x1b\[[0-9;]*[a-za-z],,g" | while read -r remote; do git branch --track "${remote#origin/}" "$remote"; done
	git fetch --all
	git pull --all
}
