#!/bin/bash

function warn() {
	printf "\033[0;33m%s$1\033[0m"
}

function regpath() {
	if [[ -z "$1" ]]; then
		warn "PATH : missing argument"
		return 1
	fi

	if [[ ! -d "$1" ]]; then
		warn "PATH: \"$1\" is not a directory"
		return 1
	fi

	if [[ -z "$PATH" ]]; then
		export PATH="$1"
	else
		if [[ ":$PATH:" != *":$1:"* ]]; then
			# echo "adding $1 to PATH"
			export PATH="$1:$PATH"
		fi
		# export path alias
		[[ -n "$2" ]] && export "$2"="$1"
	fi
}

function setup() {
	# should setup NVM before anything else
	source_file "$HOME/.nvm/nvm.sh" --silent
	source_file "$HOME/.nvm/bash_completion" --silent
	regpath "$DOTFILES/bin" "DOTFILES_BIN"
}

setup
