format = """
[░▒▓](#EC5F67)\
$username\
[](bg:#FF855A fg:#EC5F67)\
$directory\
[](fg:#FF855A bg:#eccc81)\
$git_branch\
$git_status\
[](fg:#eccc81 bg:#a8be81)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#a8be81 bg:#5d81ab)\
$docker_context\
[](fg:#5d81ab bg:#436493)\
$time\
[ ](fg:#436493)\
\n$character"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#EC5F67 fg:#272727"
style_root = "bg:#EC5F67 fg:#272727"
format = '[ 󰄛 $user ]($style)'

[directory]
style = "bg:#FF855A fg:#272727"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "~/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#a8be81"
format = '[[ $symbol ($version) ](bg:#a8be81)]($style)'

[docker_context]
symbol = " "
style = "bg:#5d81ab"
format = '[[ $symbol $context ](bg:#5d81ab)]($style) $path'

[elixir]
symbol = " "
style = "bg:#a8be81"
format = '[[ $symbol ($version) ](bg:#a8be81)]($style)'

[elm]
symbol = " "
style = "bg:#a8be81"
format = '[[ $symbol ($version) ](bg:#a8be81)]($style)'

[git_branch]
symbol = ""
style = "bg:#eccc81"
format = '[[ $symbol $branch ](bg:#eccc81 fg:#272727)]($style)'

[git_status]
style = "bg:#eccc81"
format = '[[($all_status$ahead_behind )](bg:#eccc81 fg:#272727)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](bg:#a8be81 fg:#272727)]($style)'

[haskell]
symbol = " "
style = "bg:#a8be81"
format = '[[ $symbol ($version) ](bg:#a8be81)]($style)'

[java]
symbol = " "
style = "bg:#a8be81"
format = '[[ $symbol ($version) ](bg:#a8be81)]($style)'

[julia]
symbol = " "
style = "bg:#a8be81"
format = '[[ $symbol ($version) ](bg:#a8be81)]($style)'

[nodejs]
symbol = ""
style = "bg:#a8be81"
format = '[[ $symbol ($version) ](bg:#a8be81 fg:#272727)]($style)'

[nim]
symbol = " "
style = "bg:#a8be81"
format = '[[ $symbol ($version) ](bg:#a8be81)]($style)'

[rust]
symbol = ""
style = "bg:#a8be81"
format = '[[ $symbol ($version) ](bg:#a8be81)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[   $time ](bg:#436493)]($style)'
