return {
  require("libs.ui.dressing-nvim"),
  require("libs.ui.todo-comments"),
  require("libs.ui.diffview-nvim"),
  require("libs.ui.mini-animate"),
  require("libs.ui.nvim-spectre"),
  require("libs.ui.nvim-notify"),
  require("libs.ui.bufferline"),
  require("libs.ui.noice-nvim"),
  require("libs.ui.nvim-navic"),
  require("libs.ui.telescope"),
  require("libs.ui.dashboard"),
  require("libs.ui.gitsigns"),
  require("libs.ui.whichkey"),
  require("libs.ui.barbeque"),
  require("libs.ui.lualine"),
}
