---@type LazySpec[]
return {
  require("usr.ui.noice"),
  require("usr.ui.notify"),
  require("usr.ui.zenmode"),
  require("usr.ui.windows"),
  require("usr.ui.lualine"),
  require("usr.ui.plenary"),
  require("usr.ui.winshift"),
  require("usr.ui.twilight"),
  require("usr.ui.barbeque"),
  require("usr.ui.colorizer"),
  require("usr.ui.fokus-nvim"),
  require("usr.ui.nvim-navic"),
  require("usr.ui.webdevicons"),
  require("usr.ui.mini-animate"),
  require("usr.ui.smooth-cursor"),
  require("usr.ui.mini-indentscope"),
  require("usr.ui.indent-blankline"),
}
