#!/usr/bin/env bash

alias cl="clear"
alias rm="trash"
alias ls="eza"
alias ll='eza -alF'
alias la='eza -la'
alias grep="rg"
alias cat="bat -p"
alias mx="tmux"
alias v="NVIM_APPNAME=nvmini nvim"
alias vi="NVIM_APPNAME=nvmini nvim"
alias so-bash="source ~/.bashrc"
alias so-zsh="source ~/.zshenv"
alias n="nnn -P v"
alias N="sudo nnn -P v"
alias neofetch="fastfetch"
alias x="exit"
alias nvidia-check-drm="sudo cat /sys/module/nvidia_drm/parameters/modeset"
alias cpu-check-gov="cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
alias update-initramfs="sudo dracut --force --verbose"
alias update-grub="sudo grub2-mkconfig -o /boot/grub2/grub.cfg"
alias __reset-cuda="sudo rmmod nvidia_drm && sudo modprobe nvidia_drm"
alias __sync-local-time="timedatectl set-local-rtc 1"
alias __purge-nvim-cache="rm -rf ~/.cache/nvim && rm -rf ~/.local/state/nvim"
alias __start-plasma-from-console="/usr/lib/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland"
