#!/usr/bin/env bash

# vim:fileencoding=utf-8:ft=sh

# source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# shellcheck disable=SC1090
if [ -d ~/.bashrc.d ]; then
  for rc in ~/.bashrc.d/**.sh; do
    if [ -f "$rc" ]; then
      source "$rc"
    fi
  done
fi

unset rc
