#!/usr/bin/env zsh

# NOTE: this file loaded after env

[ -s "$DOTFILES/starship/init.zsh" ] && source "$DOTFILES/starship/init.zsh"
[ -s "$DOTFILES/fzf/init.zsh" ] && source "$DOTFILES/fzf/init.zsh"
[ -s "$DOTFILES/nnn/init.zsh" ] && source "$DOTFILES/nnn/init.zsh"
[ -s "$DOTFILES/webdev/init.zsh" ] && source "$DOTFILES/webdev/init.zsh"
[ -s "$DOTFILES/alias/init.zsh" ] && source "$DOTFILES/alias/init.zsh"

bindkey -s "\em" "zmux\n"

# pnpm
export PNPM_HOME="/home/radvil/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# bun completions
[ -s "/home/radvil/.bun/_bun" ] && source "/home/radvil/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$PATH:$BUN_INSTALL/bin"
export PATH="$PATH:$HOME/.spoofdpi/bin"
