#!/usr/bin/env zsh

# NOTE: this file loaded after env

# [ -s "$DOTFILES/zsh/plug/init.zsh" ] && source "$DOTFILES/zsh/plug/init.zsh"
[ -s "$DOTFILES/omz/init.zsh" ] && source "$DOTFILES/omz/init.zsh"
[ -s "$DOTFILES/starship/init.zsh" ] && source "$DOTFILES/starship/init.zsh"
[ -s "$DOTFILES/fzf/init.zsh" ] && source "$DOTFILES/fzf/init.zsh"
[ -s "$DOTFILES/nnn/init.zsh" ] && source "$DOTFILES/nnn/init.zsh"
[ -s "$DOTFILES/webdev/init.zsh" ] && source "$DOTFILES/webdev/init.zsh"
[ -s "$DOTFILES/alias/init.zsh" ] && source "$DOTFILES/alias/init.zsh"

bindkey -s "\ew" "ami-project\n"
bindkey -s "\em" "zmux\n"

# pnpm
export PNPM_HOME="/home/radvil/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
